 # Revision

In [1]:
a1 = [11,22,33,44,55]
print(a1)
print (type(a1))

[11, 22, 33, 44, 55]
<class 'list'>


In [5]:
import numpy as np

In [6]:
arr1 = np.array(a1)       # Converting list into an array
print(arr1)

[11 22 33 44 55]


In [7]:
# Typecasting example from Python basics
num = 100
x = str(num)
print (x)
print (type(x))

100
<class 'str'>


In [10]:
print (type(arr1))

<class 'numpy.ndarray'>


In [ ]:
Elementwise operation

In [11]:
for i in a1:
    print (i*2)

22
44
66
88
110


In [12]:
a2 = [i * 2 for i in a1]
print(a2)

[22, 44, 66, 88, 110]


In [13]:
arr1**2

array([ 121,  484, 1089, 1936, 3025])

In [14]:
arr1 *arr1

array([ 121,  484, 1089, 1936, 3025])

In [15]:
arr1 + arr1

array([ 22,  44,  66,  88, 110])

In [17]:
arr1 * arr1 * arr1

array([  1331,  10648,  35937,  85184, 166375])

In [18]:
arr1    # No need to write print

array([11, 22, 33, 44, 55])

In [25]:
arr2 = np.array([1,2,3])

In [19]:
arr1 * arr2

NameError: name 'arr2' is not defined