   # Creating 2D Array

In [10]:
# Using list of lists
import numpy as np

In [6]:
m = [[0,1,2,3,4,5,6,7,8,9,10,11],[0,1,2,3,4,5,6,7,8,9,10,11]]

In [2]:
print(type(m))

<class 'list'>


In [8]:
m

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]]

In [11]:
m_arr = np.array(m)

In [12]:
m_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [13]:
type(m_arr)

numpy.ndarray

In [ ]:
# Checking the Attributes

In [14]:
m_arr.ndim

2

In [15]:
m_arr.shape

(2, 12)

In [16]:
m_arr.size            #this will always be a Integer , count of elements

24

In [18]:
z = [[0,1,2,3,4,5,6,7,8,9,10,11],[0,1,2,3,4,5,6,7,8,9,10,11],[0,1,2,3,4,5,6,7,8,9,10,11]]

In [20]:
arr4 = np.array(z)

In [21]:
arr4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [22]:
arr4.ndim

2

In [23]:
arr4.shape

(3, 12)

In [24]:
arr4.size

36

 #  Using arange() & reshape()

In [ ]:
# Using reshape() to change the array from 1D to 2D.
# Can also be changed to higher dimensions

In [25]:
arr5 = np.arange(12)

In [26]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
arr5.ndim

1

In [28]:
arr5.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
arr5.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
arr5.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [31]:
arr5.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [32]:
arr5.reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [33]:
arr5.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [34]:
arr5.reshape(12,2)         # rows * column = array size

ValueError: cannot reshape array of size 12 into shape (12,2)

In [35]:
arr5.reshape (3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

   # Using linspace() & reshape()

In [ ]:
# Using linspace() to change the array from 1D to 2D

In [36]:
arr6 = np.linspace(1,10,15).reshape(3,5)

In [37]:
arr6

array([[ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857],
       [ 4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429],
       [ 7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ]])

In [ ]:
# Checking the Attributes

In [38]:
arr6.ndim


2

In [39]:
arr6.shape

(3, 5)

In [40]:
arr6.size


15

In [ ]:
# 1D will have one[]
# 2D will have [[ ]]
# 3D will have [[[ ]]]
# By counting the opening square brackets, we can clearly identify the Dimension of Array.