  # More on 2D

In [2]:
import numpy as np

In [ ]:
# arange() Vs linspace()

In [3]:
arr1 = np.array([11,22,33])
arr1

array([11, 22, 33])

In [5]:
arr2 = np.arange(1,50,17)
arr2

array([ 1, 18, 35])

In [6]:
arr2 = np.linspace(1,50,17)      # linspace gives the number of equidistant values
arr2

array([ 1.    ,  4.0625,  7.125 , 10.1875, 13.25  , 16.3125, 19.375 ,
       22.4375, 25.5   , 28.5625, 31.625 , 34.6875, 37.75  , 40.8125,
       43.875 , 46.9375, 50.    ])

In [ ]:
# Reshaping


In [11]:
arr5 = np.linspace(1,12,12)
print(arr5)
print(type(arr5))
print(arr5.ndim)

arr6 = arr5.reshape(6,2)
print(arr5.ndim)
print(arr6.ndim)



[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
<class 'numpy.ndarray'>
1
1
2


In [12]:
arr6

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.]])

In [13]:
arr3 = np.arange(12).reshape(4,3)
arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

 # Row vector Vs Column Vector

In [14]:
arr7 = np.arange(6).reshape(1,6)                  # row vector
arr7
                        

array([[0, 1, 2, 3, 4, 5]])

In [15]:
arr8 = np.arange(6).reshape(6,1)                 # column vector
arr8

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

   # Dealing with wrong parameters

In [16]:
arr9 = np.arange(18).reshape(6,3)
arr9

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [17]:
arr9 = np.arange(18).reshape (6,-8)       # wrong parameter will be recalculated by numpy , autocorrect
arr9


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [19]:
arr9 = np.arange(18).reshape(6,9)
arr9

ValueError: cannot reshape array of size 18 into shape (6,9)

In [20]:
arr9 = np.arange(18).reshape(6,)       # missing parameter will not be recalculated by numpy
arr9

ValueError: cannot reshape array of size 18 into shape (6,)

   # Initial placeholders

   # Zeros

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros([5,5])                  #use [] for entering the dimension values

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.zeros([10,10])                  #use [] for entering the dimension values

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

   # ones

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.ones([5,7])

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

   # Identity Matrix

In [27]:
np.eye(9)                      # diagonally 1

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.eye(1)

array([[1.]])

   # diag

In [30]:
np.diag([11,22,33])

array([[11,  0,  0],
       [ 0, 22,  0],
       [ 0,  0, 33]])

In [31]:
np.diag([11,22,33,44,55,66])

array([[11,  0,  0,  0,  0,  0],
       [ 0, 22,  0,  0,  0,  0],
       [ 0,  0, 33,  0,  0,  0],
       [ 0,  0,  0, 44,  0,  0],
       [ 0,  0,  0,  0, 55,  0],
       [ 0,  0,  0,  0,  0, 66]])