   # Indexing and Slicing

# With 1D Array

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(5,12)              #last value not included
arr1

array([ 5,  6,  7,  8,  9, 10, 11])

In [3]:
arr1[0]

5

In [4]:
arr1[5]

10

In [ ]:
# Slicing

In [5]:
arr1 [0:6:2]

array([5, 7, 9])

In [6]:
# Supports negative indexing
arr1 [-1]

11

In [7]:
# arrar reversal using negative indexing
# reversal is based on index position

arr1[::-1]

array([11, 10,  9,  8,  7,  6,  5])

  # With 2D arrays

In [8]:
arr2 = np.arange(15).reshape(3,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
arr2.ndim

2

In [10]:
arr2[0]    # array[row_number_start : row_number_end(not included)]

array([0, 1, 2, 3, 4])

In [11]:
arr2[1]

array([5, 6, 7, 8, 9])

In [13]:
arr2[0 : 3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
arr4 = np.arange(50).reshape(10,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [15]:
arr4[0]

array([0, 1, 2, 3, 4])

In [16]:
arr4[3]

array([15, 16, 17, 18, 19])

In [17]:
arr4[0:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
arr4[0:5:2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

   # Slicing

In [ ]:
 # arr1[x][y]
 # array[rows][column]   

In [19]:
arr4 = np.arange(50).reshape(10,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [20]:
arr4[0][0]

0

In [21]:
arr4[2][2]

12

In [22]:
arr4[4:6][1:3]
# arr4[4:6]

array([[25, 26, 27, 28, 29]])

In [ ]:
# for intersection of rows and columns
# arr1[x][y] 
#arry[rows_start:rows_end,column_start:column_end]
arr4[4:6,1:3]

In [23]:
arr4 [4:6,1:3]

array([[21, 22],
       [26, 27]])