In [4]:
import numpy as np


  # Indexing with Boolean arrays

In [ ]:
# masking
# boolean indexing

In [2]:
arr1 = np.arange(12).reshape(3,4)

In [3]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
arr1 + 10  # this is elementwise operation


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [5]:
arr1 > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [6]:
arr1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [7]:
arr1 < 5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [8]:
arr1 % 2 == 0

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [10]:
arr1 % 2 != 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [11]:
arr1 % 3 == 0

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False]])

In [ ]:
# multiple conditions

In [12]:
arr1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# arr1 % 2 == 0
# and
# arr1 % 3 == 0

In [13]:
 (arr1 % 2 == 0) & (arr1 % 3 == 0)      # NUMPY- & for and

array([[ True, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [ ]:
# arr1 % 2 == 0
# or
# arr1 % 3 == 0

In [18]:
 arr2 = (arr1 % 2 == 0) | (arr1 % 3 == 0)      # NUMPY- |(pipe symbol) for or

In [15]:
arr1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
arr2          # boolean array- values are boolean

array([[ True, False,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True, False]])

In [20]:
arr1[(arr1 % 2 == 0) | (arr1 % 3 == 0)]

array([ 0,  2,  3,  4,  6,  8,  9, 10])

In [21]:
arr1[arr1>10]

array([11])

In [22]:
arr1[arr1 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [24]:
arr1[(arr1 % 2 == 0) & (arr1 % 3 == 0)]

array([0, 6])

  # Universal Function

In [ ]:
# Arrays must be of same shape and size

In [ ]:
# https://numpy.org/doc/stable/user/basics.ufuncs.html

In [25]:
a = np.array ([11,22,33,44,55])
b = np.array ([1,2,3,4,5])
print(a)
print(b)

[11 22 33 44 55]
[1 2 3 4 5]


In [27]:
a +10

array([21, 32, 43, 54, 65])

In [28]:
a

array([11, 22, 33, 44, 55])

In [29]:
a + b

array([12, 24, 36, 48, 60])

In [30]:
a - b

array([10, 20, 30, 40, 50])

In [31]:
a * b

array([ 11,  44,  99, 176, 275])

In [32]:
a/b

array([11., 11., 11., 11., 11.])

In [33]:
a = np.array ([11,22,33,44,55])
b = np.array ([1,2,3,4,0])
print(a)
print(b)

[11 22 33 44 55]
[1 2 3 4 0]


In [34]:
a * b

array([ 11,  44,  99, 176,   0])

In [35]:
a / b

C:\Users\joshi\AppData\Local\Temp\ipykernel_12328\1286629031.py:1: RuntimeWarning: divide by zero encountered in divide
  a / b


array([11., 11., 11., 11., inf])

In [ ]:
a = np.array ([11,22,33,44,55])
b = np.array ([1,2,3,4,0])
print(a)
print(b)

In [36]:
b / a

array([0.09090909, 0.09090909, 0.09090909, 0.09090909, 0.        ])

In [ ]:
a = np.array ([11,22,33,44,0])
b = np.array ([1,2,3,4,0])
print(a)
print(b)

In [37]:
a/b

C:\Users\joshi\AppData\Local\Temp\ipykernel_12328\1348051284.py:1: RuntimeWarning: divide by zero encountered in divide
  a/b


array([11., 11., 11., 11., inf])

In [38]:
a = np.array ([11,22,33,44])
b = np.array ([1,2,3,4,5])
print(a)
print(b)

[11 22 33 44]
[1 2 3 4 5]


In [39]:
a+b

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [ ]:
# https://numpy.org/doc/stable/user/quickstart.html#broadcasting-rules

In [5]:
# /HW
# 1. # slice the array to get below name
s = np.array([['Priya', 'Rohit', 'Aryan'],
       ['Neha', 'Avni', 'Akash'],
       ['Arjun', 'Riya', 'Devanshi']])


# 1. 'Priya', 'Rohit', 'Aryan'
# 2. 'Riya','Devanshi'
# 3. 'Neha', 'Avni', 'Akash' 'Arjun', 'Riya', 'Devanshi'
# 4. 'Avni'
# 5. 'Neha'

# 2. Use masking to get the values
score = np.random.randint(10,100,15).reshape(5,3)
# 1. find all scores > 50
# 2. find all scores <35

In [42]:
s[0]

array(['Priya', 'Rohit', 'Aryan'], dtype='<U8')

In [6]:
s[1:,:]

array([['Neha', 'Avni', 'Akash'],
       ['Arjun', 'Riya', 'Devanshi']], dtype='<U8')

In [44]:
score

array([[39, 14, 83],
       [10, 46, 24],
       [99, 26, 95],
       [75, 84, 80],
       [98, 93, 78]])

In [45]:
score[score>50]

array([83, 99, 95, 75, 84, 80, 98, 93, 78])

In [46]:
score[score<35]

array([14, 10, 24, 26])

In [48]:
np.random.randint(10,100,15).reshape(5,3)

array([[14, 82, 25],
       [74, 80, 88],
       [28, 25, 81],
       [63, 21, 81],
       [40, 57, 76]])