   # Aggregate Function

In [1]:
import numpy as np


In [2]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,5])
print(a)
print(b)

[11 22 33 44 55]
[1 2 3 4 5]


In [3]:
a + b

array([12, 24, 36, 48, 60])

In [4]:
a * b

array([ 11,  44,  99, 176, 275])

In [5]:
np.sum(a)

165

In [6]:
np.min(a)

11

In [7]:
np.min(b)

1

In [8]:
np.max(a)

55

In [9]:
np.max(b)

5

In [10]:
np.mean(a)

33.0

In [11]:
np.mean(b)

3.0

In [ ]:
 # 2D Array

In [12]:
len(np.arange(10,60,2))

25

In [15]:
arr1 = np.arange(10,60,2).reshape(5,5)

In [16]:
arr1

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [17]:
np.sum(arr1,axis= None)

850

In [18]:
np.sum(arr1,axis=0)    # sum of columns

array([150, 160, 170, 180, 190])

In [19]:
np.sum(arr1,axis=1)    # sum of rows

array([ 70, 120, 170, 220, 270])

In [20]:
np.max(arr1)

58

In [21]:
np.max(arr1, axis=1)

array([18, 28, 38, 48, 58])

In [23]:
np.max(arr1,axis=0)

array([50, 52, 54, 56, 58])

In [25]:
np.mean(arr1,axis = 1)

array([14., 24., 34., 44., 54.])

In [26]:
score = np.random.randint(10,100,15).reshape(5,3)

In [27]:
score

array([[66, 17, 99],
       [30, 40, 98],
       [36, 88, 44],
       [55, 33, 58],
       [61, 15, 17]])

In [28]:
np.sum(score,axis=0)  # column     # y axis---0, x axis---1

array([248, 193, 316])

In [29]:
np.sum(score,axis=1)  # rows

array([182, 168, 168, 146,  93])

In [30]:
np.mean(score,axis=1)

array([60.66666667, 56.        , 56.        , 48.66666667, 31.        ])

In [31]:
np.min(score,axis=1)

array([17, 30, 36, 33, 15])

In [32]:
np.max(score,axis=0)

array([66, 88, 99])

   # Logical Functions

In [ ]:
# any : all the elements should be zero for output to be False : behaves like OR
# all : all the elements should be non zero for output to be True : behaves like AND
# True and False

In [33]:
score = np.random.randint(10,100,15).reshape(5,3)

In [34]:
score

array([[20, 52, 81],
       [16, 45, 76],
       [82, 45, 68],
       [47, 69, 26],
       [89, 41, 41]])

In [35]:
arr5 = np.array([11,22,33,0,55])
np.any(arr5)

True

In [36]:
arr5 = np.array([0,0,0,0,0,55])
np.any(arr5)

True

In [37]:
arr5 = np.array([0,0,0,0,0])
np.any(arr5)

False

In [ ]:
# all


In [38]:
arr5 = np.array([11,22,33,0,55])
np.all(arr5)

False

In [40]:
arr5 = np.array([11,22,33,55])
np.all(arr5)

True