   # Broadcasting

In [2]:
import numpy as np

In [3]:
arr1 = np.arange(15).reshape(5,3)
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [4]:
arr2 = np.arange(15).reshape(3,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [6]:
x = np.array([10,20,30])
y = np.array([[1],[2],[3],[4]])

In [7]:
x.ndim
x

array([10, 20, 30])

In [8]:
y.ndim
y

array([[1],
       [2],
       [3],
       [4]])

In [9]:
x + y

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

In [10]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [11]:
arr3 = np.array([100,200,300])
arr3

array([100, 200, 300])

In [12]:
arr1 + arr3

array([[100, 201, 302],
       [103, 204, 305],
       [106, 207, 308],
       [109, 210, 311],
       [112, 213, 314]])

In [13]:
a = np.arange(10)
b = np.arange(5)

In [14]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
b

array([0, 1, 2, 3, 4])

In [16]:
a + b


ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [17]:
arr5 = np.arange(12).reshape(4,3)
arr5

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
arr6 = np.arange(4)
arr6

array([0, 1, 2, 3])

In [19]:
arr5 + arr6

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

 # Splitting

In [ ]:
# Splitting 1D array

In [20]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.split(x,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [22]:
z = np.arange(12)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
np.split(z,4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [24]:
np.split(z,2)

[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [25]:
np.split(z,10)

ValueError: array split does not result in an equal division

In [26]:
np.split(z,12)

[array([0]),
 array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9]),
 array([10]),
 array([11])]

In [27]:
np.split(z,3)[2]   # Accessing the subparts after splitting the array

array([ 8,  9, 10, 11])

In [28]:
np.split(z,4,axis = 0)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [29]:
np.split(z,4)    # default axis is zero

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [ ]:
#Splitting a 2D array


In [30]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
np.split(x,4)         # default axis is zero

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [32]:
np.split(x,4,axis=0)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [33]:
np.split(x,4,axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [34]:
y = np.arange(18).reshape(6,3)
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [35]:
np.split(y,3,axis=0)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [36]:
np.split(y,3,axis=1)

[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])]