In [1]:
import numpy as np

In [2]:
data = np.loadtxt('fitbit.txt', dtype = 'str')   # because of date data type,we make it as a string

In [3]:
#numpy array is?
# a. Homogenous array
# b. Heterogenous array

# List is Heterogenous
# numpy array is homogenous.

In [4]:
data

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8

In [5]:
print(type(data))

<class 'numpy.ndarray'>


In [6]:
data.ndim

2

In [7]:
data.shape     # rows = 26 and columns = 7

(26, 7)

In [8]:
data.size

182

In [9]:
data[0]

array(['06-10-2017', '5464', '200', '181', '6', '0', '68'], dtype='<U10')

In [10]:
data[1]

array(['07-10-2017', '7167', '200', '208', '6', '0', '68'], dtype='<U10')

   # Data Cleaning

In [11]:
# data has no header
# all the data is in STRING type

In [12]:
data


array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8

In [13]:
data. T            # transpose

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017'],
       ['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
        '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
        '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
        '6347', '5911'],
       ['200', '200', '300', '100', '300', '300', '100', '200', '200',
        '300', '300', '300', '300', '200', '200', '200', '300', '300',
        '100', '100', '300', '300', '300', '100', '200', '200'],
       ['181', '208', '341', '190', '307', '302', '198', '201', '195',
        '327', '331', '318', '344', '204', '180', '201', '32

In [14]:
data.T[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [15]:
data.T[1]

array(['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
       '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
       '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
       '6347', '5911'], dtype='<U10')

In [16]:
tup_1 = (11,22,33,44)       # Packing a tuple
print(tup_1[0])
print(tup_1[1])
print(tup_1[2])

11
22
33


In [17]:
a,b,c,d = tup_1         # Unpacking a tuple
print(a)
print(b)

11
22


In [18]:
date,step_count,mood,calories_burned,hours_of_sleep,bool_of_active,weight_kg= data.T

In [19]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [20]:
print(date)

['06-10-2017' '07-10-2017' '08-10-2017' '09-10-2017' '10-10-2017'
 '11-10-2017' '12-10-2017' '13-10-2017' '14-10-2017' '15-10-2017'
 '16-10-2017' '17-10-2017' '18-10-2017' '19-10-2017' '20-10-2017'
 '21-10-2017' '22-10-2017' '23-10-2017' '24-10-2017' '25-10-2017'
 '26-10-2017' '27-10-2017' '28-10-2017' '29-10-2017' '30-10-2017'
 '31-10-2017']


In [21]:
step_count

array(['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
       '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
       '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
       '6347', '5911'], dtype='<U10')

In [22]:
step_count.dtype

dtype('<U10')

In [23]:
step_count = np.array(step_count,dtype='int')

In [24]:
step_count

array([5464, 7167, 9874, 4969, 8538, 9875, 4662, 6310, 7556, 9073, 9690,
       9146, 9752, 6974, 5619, 6889, 8616, 9131, 4211, 4291, 8569, 9337,
       8475, 4510, 6347, 5911])

In [25]:
step_count.dtype

dtype('int32')

 #  Next day: Data types in Numpy

In [26]:
# https://numpy.org/doc/stable/user/basics.types.html

In [27]:
step_count.dtype

dtype('int32')

In [28]:
type(step_count)

numpy.ndarray

In [29]:
step_count

array([5464, 7167, 9874, 4969, 8538, 9875, 4662, 6310, 7556, 9073, 9690,
       9146, 9752, 6974, 5619, 6889, 8616, 9131, 4211, 4291, 8569, 9337,
       8475, 4510, 6347, 5911])

In [30]:
# Changing the string datatype to 'int'

In [31]:
step_count = np.array(step_count,dtype='int')

In [32]:
step_count

array([5464, 7167, 9874, 4969, 8538, 9875, 4662, 6310, 7556, 9073, 9690,
       9146, 9752, 6974, 5619, 6889, 8616, 9131, 4211, 4291, 8569, 9337,
       8475, 4510, 6347, 5911])

In [33]:
step_count.dtype

dtype('int32')

In [34]:
# Changing the data type of other parameters to 'int'


In [35]:
calories_burned = np.array(calories_burned,dtype='int')
hours_of_sleep = np.array(hours_of_sleep,dtype = 'int')
weight_kg = np.array(weight_kg,dtype='int')

In [36]:
calories_burned

array([181, 208, 341, 190, 307, 302, 198, 201, 195, 327, 331, 318, 344,
       204, 180, 201, 329, 315, 197, 184, 328, 322, 327, 148, 235, 184])

In [37]:
calories_burned.dtype

dtype('int32')

In [38]:
hours_of_sleep

array([6, 6, 5, 8, 5, 5, 8, 6, 6, 5, 5, 5, 5, 6, 6, 6, 5, 5, 8, 8, 5, 5,
       5, 8, 6, 6])

In [39]:
hours_of_sleep.dtype

dtype('int32')

In [40]:
weight_kg

array([68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68])

In [41]:
weight_kg.dtype

dtype('int32')

In [42]:
# focussing on "mood" data
# data is in numerical form but is repetative
# checking the patterns of data

In [43]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [44]:
# mood data is categorical

In [45]:
# 100 = sad
# 200 = neutral
# 300 = happy

In [46]:
np.unique(mood)

array(['100', '200', '300'], dtype='<U10')

In [47]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [48]:
mood == '100'       # 100 = sad

array([False, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False,  True, False, False])

In [49]:
mood == '100'    # 100 = sad
mood[mood == '100'] = 'sad'

In [50]:
mood == '200'    # 200 = neutral

array([ True,  True, False, False, False, False, False,  True,  True,
       False, False, False, False,  True,  True,  True, False, False,
       False, False, False, False, False, False,  True,  True])

In [51]:
mood == '200'
mood[mood == '200'] = 'neutral'

In [52]:
mood == '300'   # 300 = happy

array([False, False,  True, False,  True,  True, False, False, False,
        True,  True,  True,  True, False, False, False,  True,  True,
       False, False,  True,  True,  True, False, False, False])

In [53]:
mood == '300'
mood[mood == '300'] = 'happy'

In [54]:
mood

array(['neutral', 'neutral', 'happy', 'sad', 'happy', 'happy', 'sad',
       'neutral', 'neutral', 'happy', 'happy', 'happy', 'happy',
       'neutral', 'neutral', 'neutral', 'happy', 'happy', 'sad', 'sad',
       'happy', 'happy', 'happy', 'sad', 'neutral', 'neutral'],
      dtype='<U10')

   # Analysing data

In [55]:
data

array([['06-10-2017', '5464', 'neutral', '181', '6', '0', '68'],
       ['07-10-2017', '7167', 'neutral', '208', '6', '0', '68'],
       ['08-10-2017', '9874', 'happy', '341', '5', '0', '68'],
       ['09-10-2017', '4969', 'sad', '190', '8', '0', '68'],
       ['10-10-2017', '8538', 'happy', '307', '5', '0', '68'],
       ['11-10-2017', '9875', 'happy', '302', '5', '0', '68'],
       ['12-10-2017', '4662', 'sad', '198', '8', '0', '68'],
       ['13-10-2017', '6310', 'neutral', '201', '6', '0', '68'],
       ['14-10-2017', '7556', 'neutral', '195', '6', '0', '68'],
       ['15-10-2017', '9073', 'happy', '327', '5', '0', '68'],
       ['16-10-2017', '9690', 'happy', '331', '5', '0', '68'],
       ['17-10-2017', '9146', 'happy', '318', '5', '0', '68'],
       ['18-10-2017', '9752', 'happy', '344', '5', '0', '68'],
       ['19-10-2017', '6974', 'neutral', '204', '6', '0', '68'],
       ['20-10-2017', '5619', 'neutral', '180', '6', '0', '68'],
       ['21-10-2017', '6889', 'neutral', '201',

In [56]:
step_count

array([5464, 7167, 9874, 4969, 8538, 9875, 4662, 6310, 7556, 9073, 9690,
       9146, 9752, 6974, 5619, 6889, 8616, 9131, 4211, 4291, 8569, 9337,
       8475, 4510, 6347, 5911])

In [57]:
np.max(step_count)

9875

In [58]:
np.min(step_count)

4211

In [59]:
np.mean(step_count)

7344.461538461538

In [60]:
np.argmax(step_count)

5

In [61]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [62]:
date[5]

'11-10-2017'

In [63]:
mood[5]

'happy'

In [ ]:
# step count relation with mood of the customer

In [64]:
mood == 'sad'

array([False, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False,  True, False, False])

In [65]:
mood[mood == 'sad']          # Boolean masking for filtering data

array(['sad', 'sad', 'sad', 'sad', 'sad'], dtype='<U10')

In [66]:
len(mood[mood == 'sad'])

5

In [67]:
len(mood[mood == 'neutral'])

9

In [68]:
len(mood[mood == 'happy'])

12

In [69]:
np.unique(mood,return_counts = True)

(array(['happy', 'neutral', 'sad'], dtype='<U10'),
 array([12,  9,  5], dtype=int64))

In [70]:
step_count[mood == 'sad']

array([4969, 4662, 4211, 4291, 4510])

In [71]:
np.mean(step_count[mood == 'sad'])

4528.6

In [72]:
np.mean(step_count[mood == 'neutral'])

6470.777777777777

In [73]:
np.mean(step_count[mood == 'happy'])

9173.0

In [74]:
date[np.argmax(step_count)]

'11-10-2017'

In [75]:
mood == 'happy'

array([False, False,  True, False,  True,  True, False, False, False,
        True,  True,  True,  True, False, False, False,  True,  True,
       False, False,  True,  True,  True, False, False, False])

In [76]:
date[mood == 'happy']

array(['08-10-2017', '10-10-2017', '11-10-2017', '15-10-2017',
       '16-10-2017', '17-10-2017', '18-10-2017', '22-10-2017',
       '23-10-2017', '26-10-2017', '27-10-2017', '28-10-2017'],
      dtype='<U10')

In [77]:
step_count[mood == 'happy']

array([9874, 8538, 9875, 9073, 9690, 9146, 9752, 8616, 9131, 8569, 9337,
       8475])

In [78]:
weight_kg[mood == 'happy']

array([68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68])